### ISSUE TITLE
Error when building the example CIFAR_image_detection

### ISSUE THREAD

**Issue by davidmallasen** [rkuang9/OrionNN#6]
Hello,

I was trying out the repo and building the `CIFAR_image_detection.h` example, and I'm stuck after fixing a few issues with missing imports. The error I'm getting is the following:

~~~
FLARE/examples/../flare/layers/flatten.ipp:52:36: error: no match for ‘operator==’ (operand types are ‘const Dimensions’ {aka ‘const Eigen::DSizes<long int, 2>’} and ‘const Dimensions’ {aka ‘const Eigen::DSizes<long int, 4>’})
   52 |     fl_assert(this->Z.dimensions() == gradients.dimensions(),
~~~

I'm using eigen 3.4.0 and the latest version of FLARE. Would you have any idea why this is failing @rkuang9 ?

EDIT: You can find my setup here: https://github.com/davidmallasen/FLARE/tree/cifar_example

Thanks!

Best regards,
David

**Comment by rkuang9** [comment]
Are you able to run learn_addition.hpp?

Can you post the error when trying to run the following (will not compile due to dimension mismatch)?
```
fl::Tensor<2> a(1, 3);
a.setValues({{1, 2, 3}});

fl::Tensor<3> b(2, 3, 1);
b.setRandom();
std::cout << (a.dimensions() == b.dimensions());
```

I'll need to get back to you after reinstalling opencv on my machine.

**Comment by davidmallasen** [comment]
Hello @rkuang9 , thanks for the quick response.

The learn_addition example does work, yes.

The error when compiling that piece of code is:
~~~
FLARE/examples/main.cpp:11:34: error: no match for ‘operator==’ (operand types are ‘const Dimensions’ {aka ‘const Eigen::DSizes<long int, 2>’} and ‘const Dimensions’ {aka ‘const Eigen::DSizes<long int, 3>’})
   11 |     std::cout << (a.dimensions() == b.dimensions());
      |                   ~~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~~
      |                               |                 |
      |                               DSizes<[...],2>   DSizes<[...],3>
~~~

**Comment by rkuang9** [comment]
In the example, the flatten layer's output is a rank 2 tensor but it's incorrectly receiving a rank 4 gradient tensor from the softmax Dense. I will see if I can figure out why and fix it. Is the MNIST_digit_detection.h example also giving the same error (dataset https://www.kaggle.com/datasets/scolianni/mnistasjpg/data)?

**Comment by rkuang9** [comment]
I've pushed a fix, please see https://github.com/rkuang9/FLARE/commit/efe520dd18dba5e1af13b566e13fdf3a735b4bd2. Can you confirm that the CIFAR_image_detection.h example is working?

**Comment by davidmallasen** [comment]
Now it is working @rkuang9, thanks! I have it in https://github.com/davidmallasen/FLARE/tree/cifar_example
